spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  flyway:
    baseline-on-migrate: true